### PR TITLE
New platform!

### PR DESCRIPTION
**Pull request by josepostiga**
Hey guys!

This PR transfers our website to the Jigsaw platform, which will enable us to use (for example) Netlify to publish it and keep it active.

If this gets merged, I request that the domain's DNS servers be changed to the following:
dns1.p08.nsone.net
dns2.p08.nsone.net
dns3.p08.nsone.net
dns4.p08.nsone.net

This will allow for traffic to reach Netlify's servers.

### CODE REVIEW

**Comment by ijpatricio** [comment]
Hello @josepostiga,

Nice job.

Why changing all the DNS, and not a simple A record for www.laravel.pt and laravel.pt?

**Comment by josepostiga** [comment]
Quoting from https://www.netlify.com/docs/dns:
> Netlify offers the option to handle DNS management for you. This enables advanced subdomain automation and deployment features, and ensures that your site uses our CDN for the root domain as well as subdomains like www.

**Comment by ijpatricio** [comment]
I see. That's good when we don't have such service.

In our case, we have dns management, and a full linux shared hosting, with email, ftp, and so on... (that i'm providing)

The way I see it, we should keep it, and just having a CNAME record then..

Give me the default domain netlify gave to the project, and I'll point it, without having to loose what we already have

**Comment by josepostiga** [comment]
Why does this project needs a full Linux shared hosting, with FTP, E-mail and all those services, if it's only a landing page to direct people to the Discord server, to the Youtube page and to link to other site/repositories?

And if it has all those things, why is the site down?

Anyway, here's the info you asked: https://laravel-portugal.netlify.com/

**Comment by ijpatricio** [comment]
The domain is still pointing to the vps that we stopped using.

We don't even need netlify, as we have all this. I just don't see the point in changing the dns management.

If we're going to user netlify, is as simple as a cname entry.

The url you provided is not working...
image

**Comment by josepostiga** [comment]
The site is yet to be deployed because is pending the merge of this PR.

Also, this PR is one solution to make the site available, without any cost to any of the members. If it's the will of the other members to use other platform or your shared Linux servers, then by all means just use it.

The only thing I'd like to see is the site back online.

**Pull request merged**
