### PR TITLE
Add Gihub icon

### LINKED ISSUE #13: Missing github link on header
We should consider add a GitHub link here:

screenshot 2018-11-16 at 14 47 58

### PR DESCRIPTION
**Pull request by skoyah**
This PR resolves #13.

### CODE REVIEW

**Comment by nunomaduro** [comment]
@skoyah @josepostiga There is a reason why we are merging this on `develop`?

**Comment by skoyah** [comment]
I thought you wanted the GitHub icon on the page.

**Comment by nunomaduro** [comment]
We want the GitHub icon, but you should target `master` instead of `develop`. I am missing something @josepostiga ?

**Comment by skoyah** [comment]
This was the way they wanted me to PR. Against develop. But I can start PR master branch if you guys want.

**Comment by josepostiga** [comment]
Yes. The master auto deploys to the server so, to avoid any kind of problem, first we merge to master so that it can be tested and then merged to master by someone with the right permissions. 

I know that this is a small change, without major side effects, but it’s a good practice.

**Comment by nunomaduro** [comment]
"first we merge to master so that it can be tested", tested by what?

**Comment by josepostiga** [comment]
I meant “first merge to develop”. But I don’t really have a strong reason why not merge to master. But the branch develop was created for this reason, I guess. No?

Right now there’s no real reason to use the develop but if other functionalities get added there might be more reasons to use develop before going to master.

**Comment by nunomaduro** [comment]
I don't see any reason why we should merge it with `develop` since we are talking about a static page.

Next PR's should target to `master` directly.

**Comment by skoyah** [comment]
Got it @nunomaduro!

**Pull request merged**
