### PR TITLE
chore(*): updating composer and npm, installing dusk, laracasts utili…

### PR DESCRIPTION
**Pull request by ijpatricio**
updating composer and npm
installing dusk, laracasts utilities, tailwind
homepage tests, 
starting community-links

### CODE REVIEW

**Comment by quetzyg** [comment]
You should have split this into smaller pull requests, each one for one task:
- Cleanup
- Update dependencies
- Add new dependencies
- Etc

**Comment by ijpatricio** [comment]
Sure, sorry about that. Is it still feasible, and from now on I will do such?

Did you pull it, everything ok?

**Comment by quetzyg** [comment]
I would prefer to close this one and do multiple smaller ones, unless a brave soul wants to go through this one :joy:

**Comment by ijpatricio** [comment]
Please bare with me :)

So after a composer update i shoul do a commit and PR??

A segunda, 9/07/2018, 18:17, Quetzy Garcia <notifications@github.com>
escreveu:

**Comment by quetzyg** [comment]
Yeah, for example. The idea is to keep different things/scopes separate.

**Comment by ijpatricio** [comment]
Will remember that!!

Despite a 37/39 files..

Its pretty basic stuff, so dont let that number scare you lol

Lets wait a brave soul :) :)

A segunda, 9/07/2018, 19:31, Quetzy Garcia <notifications@github.com>
escreveu:

**Comment by nsenica** [comment]
I'll give it a try :)

**Comment by josepostiga** [comment]
@nsenica has done a breakdown of this PR so I'll just close this and we can work based on the others.

**Comment by ijpatricio** [comment]
Aqui está uma boa referência para consultar

https://twitter.com/freekmurze/status/1313965540621377536

**Pull request closed without merging**
